name: Sanity

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  sanity:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install black
          python3 -m pip install mypy

      - name: Run compileall
        run: python3 -m compileall src

      - name: Run mypy
        run: python3 -m mypy --strict src

      - name: Check Black
        run: python3 -m black --check src
